### ISSUE TITLE
Missing Widget Positions (left and right sidebar)

### ISSUE THREAD

**Issue by jovinmaneja** [iGovPhil/gwt-wordpress#10]
gud day!

just downloaded the new template 25.1.. i have an issue about page template selection there is no template like right sidebar, left sidebar, default template and full width... unlike the previous versions of the gwt template there is a selection of that... same with version 25.0

can you fix or add the feature?  btw i'm using wp 4.7.3

thanks

**Comment by v0j** [comment]
With the version 25.1 we have added a dynamic loading of widget per region in which if there is a widget exists on the specific region, the widget will automatically display on the region.

We also removed the theme option selection in theme settings for the Left and Right sidebar widget region since it is not needed anymore.

Let me know if you have further questions.

**Comment by jovinmaneja** [comment]
thanks!
