### ISSUE TITLE
Image slider not loading

### ISSUE THREAD

**Issue by miokeosce** [iGovPhil/gwt-wordpress#11]
i want to ask the real reason why my post on my site doesn't load or show any images that's been uploaded. it occurs on all post thats been uploaded. our site is www.angono.gov.ph

Thank you!

**Comment by v0j** [comment]
Please update your gwt-wordpress v25.2.

**Comment by neoxander** [comment]
Same issue. How did you solve this?

**Comment by v0j** [comment]
Can you ellaborate on your issue? Your issue may or may not be the same as the previous one.

Also, what version of GWT do you use?
Can you also provide a link of your site?

**Comment by neoxander** [comment]
Hi Sir,

The version is 25.2, this is the link of the site pcic.gov.ph

**Comment by v0j** [comment]
As per 25.2 we simplified the Slider Images fields due to frequent confusion of the uploading of the content.

To add images in the slider, you should upload/select images in Featured Image.

![screen shot 2017-11-08 at 2 44 52 pm](https://user-images.githubusercontent.com/7617623/32535052-67b7c5ac-c493-11e7-9954-de5d85c8d6e1.png)

**Comment by neoxander** [comment]
Yeah got it! The image should be on featured image, unlike in the previous version we just use the slider url for the images... Thanks for the help! :-)
